theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
fontsize_formats: "8pt 10pt 12pt 14pt 18pt 24pt 36pt"
plugins:
  - table
  - fullscreen